{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Risks",
        "Service": "/RiskMobile/Services/RiskManagementService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "title": "#Control:title/#Value",
        "prio": "#Control:prio/#Value",
        "descr": "#Control:descr/#Value",
        "impact": "#Control:impact/#Value",
        "criticality": "#Control:criticality/#Value",
        "supplier_BusinessPartner": "#Control:supplier_BusinessPartner/#SelectedValue"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/RiskMobile/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/RiskMobile/Actions/UpdateEntityFailureMessage.action"
}