{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Mitigations",
        "Service": "/RiskMobile/Services/RiskManagementService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "createdAt": "#Control:createdAt/#Value",
        "createdBy": "#Control:createdBy/#Value",
        "description": "#Control:description/#Value",
        "owner": "#Control:owner/#Value",
        "timeline": "#Control:timeline/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/RiskMobile/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/RiskMobile/Actions/UpdateEntityFailureMessage.action"
}